# Generated by Django 6.1.1 on 2026-09-13 05:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('key', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, default='', max_length=300)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=40)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', '排队中'), ('running', '运行中'), ('done', '完成'), ('failed', '失败'), ('canceled', '已取消')], db_index=True, default='pending', max_length=12)),
                ('progress', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('message', models.CharField(blank=True, default='', max_length=300)),
                ('log', models.TextField(blank=True, default='')),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('returncode', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ScoreSnapshot',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=40)),
                ('model', models.CharField(blank=True, default='', max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('status_label', models.CharField(blank=True, default='', max_length=20)),
                ('signal', models.CharField(blank=True, default='', max_length=30)),
                ('price', models.FloatField(blank=True, null=True)),
                ('pe', models.FloatField(blank=True, null=True)),
                ('pb', models.FloatField(blank=True, null=True)),
                ('pe_range', models.CharField(blank=True, default='', max_length=30)),
                ('pb_range', models.CharField(blank=True, default='', max_length=30)),
                ('growth', models.FloatField(blank=True, null=True)),
                ('kline_last_date', models.CharField(blank=True, default='', max_length=10)),
                ('in_watchlist', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, default='', max_length=160)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
