# Generated by Django 6.1.1 on 2026-09-13 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_stockgroup_stockgroupmember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppSetting',
        ),
        migrations.DeleteModel(
            name='ScoreSnapshot',
        ),
    ]
