# Generated by Django 6.1.1 on 2026-09-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_delete_appsetting_delete_scoresnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportArtifact',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=40)),
                ('model', models.CharField(blank=True, default='', max_length=20)),
                ('file_name', models.CharField(blank=True, default='', max_length=140)),
                ('size_kb', models.IntegerField(default=0)),
                ('data_last_date', models.CharField(blank=True, default='', max_length=10)),
                ('generated_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
